### PR TITLE
Remove buttons and add button features for Rasberry Pi

### PR DESCRIPTION
**Pull request by vaarvik**

### CODE REVIEW

**Review by eirikhc — APPROVED** [review]
All done! Here we go!

**Review by Torsteim8955 — COMMENTED** [review]
You need to add RPi to requirements.txt

Everything else looks good!

**Comment by vaarvik** [comment]
> You need to add RPi to requirements.txt
> 
> Everything else looks good!

Good point @Torsteim8955. Just found out that RPi only can be installed (and is installed by default) on a Raspberry Pi. Which means that when we merge this we won't be able to make the code run on any other computer than on a Raspberry Pi. Going to use the Raspberry Pi VM we have created for development from now on. Should probably find a solution for how to make it possible to start, stop and go next on the VM without the external buttons though, but that's something we can look into in the next development phase after the hospital have started using the prototype.

**Review by Torsteim8955 — APPROVED** [review]
Looks good!

**Pull request merged**
